language: cpp
os: linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - cmake
    - python3-dev
    - python3-numpy-dev
    - swig
    - libeigen3-dev
    - liblapack-dev
    - python3-matplotlib

matrix:
  include:
    # In source build
    - script:
      - alias python=python3
      - cmake -DCMAKE_CXX_COMPILER=g++-6 -DPYTHON_EXECUTABLE=`which python3` .
      - make
    # Out of source build
    - script:
      - alias python=python3
      - mkdir build
      - cd build
      - cmake -DCMAKE_CXX_COMPILER=g++-6 -DPYTHON_EXECUTABLE=`which python3` ../
      - make

