language: cpp
os: linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - cmake
    - libgtest-dev
    - python-dev
    - python-numpy-dev
    - python-matplotlib
    - python-six
    - python-tk
    - python3-dev
    - python3-numpy-dev
    - python3-matplotlib
    - python3-six
    - python3-pip
    - python3-venv
    - python3-setuptools
    - swig
    - libeigen3-dev
    - liblapack-dev

matrix:
  include:
    # Python2: Out of source build
    - script:
      - mkdir build
      - (cd build && cmake -DCMAKE_CXX_COMPILER=g++-6 -DWITH_TESTS=ON ../ )
      - make -C build
      - make -C build check
    # Python3: In source build
    - script:
      - cmake -DCMAKE_CXX_COMPILER=g++-6 -DWITH_TESTS=ON -DPYTHON_EXECUTABLE=`which python3` .
      - make
      - make check
    # Python3: Out of source build
    - script:
      - alias python=python3
      - mkdir build
      - (cd build && cmake -DCMAKE_CXX_COMPILER=g++-6 -DWITH_TESTS=ON -DPYTHON_EXECUTABLE=`which python3` ../ )
      - make -C build
      - make -C build check
    # Python3: Pip user install
    - script:
      - CXX=g++-6 CC=gcc-6 pip3 install -v --user .
      - (cd demo && python3 -mlfa_lab)
    # Python3: venv install
    - script:
      - python3 -mvenv myenv
      - (source myenv/bin/activate; CXX=g++-6 CC=gcc-6 pip -v install .)
      - (source myenv/bin/activate; cd demo; python -mlfa_lab)

